### ISSUE TITLE
Timeline with mentions [New feature]

### ISSUE THREAD

**Issue by zincurat** [ihabunek/toot#183] opened 2021-01-20 06:10 UTC
We have already home/local/global timelines and they work really well. I propose to add timeline with notifications (commented, boosted, favourited, polls, followed) and direct messages tab. Now it's hard to react to answer.

**Comment by ruario** [comment] 2022-11-20 18:49
Sounds like a dupe of https://github.com/ihabunek/toot/issues/147

**Comment by ihabunek** [comment] 2022-12-13 13:23
Closing as duplicate.

**Closed** 2022-12-13 13:22 UTC
