### ISSUE TITLE
Issue with using toot in a crontab.

### ISSUE THREAD

**Issue by Iratu** [ihabunek/toot#11] opened 2017-04-27 00:26 UTC
I've made a script to automagically upload a random image it downloads from the booru I host, when I manually run the script it works fine, I've been trying a lot of different things to get it running.

Error: 
`usage: toot post [-h] [-m MEDIA] [-v VISIBILITY] text
toot post: error: unrecognized arguments: `

For some reason it doesn't even give me a reason as to why it is failing.

Code: 
```#!/bin/bash
cd /home/iratu/randomchen/;
file=$(curl -s 'https://atfbooru.ninja/posts.json?tags=chen+solo+order:random+limit:1+-rating:safe&ms=1&login=Iratu&api_key=kG5eoWTEyz-DIRGXYcSsLz6bRb4d1TSkmUS7oYlaNRc');
fileurl=$(echo $file | grep -Po '"file_url":.*?[^\\]",' | perl -pe 's/"file_url"://; s/^"//; s/",$//');
filename=$(echo $file | grep -Po '"md5":.*?[^\\]",' | perl -pe 's/"md5"://; s/^"//; s/",$//');
fileext=$(echo $file | grep -Po '"file_ext":.*?[^\\]",' | perl -pe 's/"file_ext"://; s/^"//; s/",$//');
wget --quiet https://atfbooru.ninja$fileurl;
/usr/local/bin/toot post -m $filename'.'$fileext "#chen #loli #automated https://atfbooru.ninja"$fileurl;
rm /home/iratu/randomchen/$filename'.'$fileext;
exit 0;
```
when I change the toot post to just "toot" it'll output the list of commands I can use with no errors but when I try to add something like "whoami" it'll give the exact same error as the command in the code block.

**Comment by chaica** [comment] 2017-05-02 10:08
#13 is I guess a duplicate of this one, the issue will be the same

**Comment by ihabunek** [comment] 2017-05-07 08:32
The problem here is my method of detecting if there's anything piped in. When run via crontab `sys.stdin.isatty()` returnes False, which causes the contents of stdin (an empty string) to be added to commandline arguments.

That's why the argument parser returne the weird error:
```
error: unrecognized arguments:
```

That's the empty string at the end of that error message.

**Closed** 2017-05-07 08:44 UTC

**Comment by ihabunek** [comment] 2017-05-07 08:47
@chaica @Iratu This is fixed in 0.11.0. Please upgrade and test.

**Comment by chaica** [comment] 2017-05-07 08:50
works like a charm for me! Thanks a lot!

**Comment by Iratu** [comment] 2017-05-07 13:12
Works great, thanks! 👍
