### ISSUE TITLE
data files get added to wrong directory

### ISSUE THREAD

**Issue by dadosch** [ihabunek/toot#149] opened 2020-01-21 10:59 UTC
when installing using 
`python setup.py install --root="somedir/" --optimize=1 --skip-build`

the following files are in somedir, that should not belong there:

somedir/usr/CHANGELOG.md
somedir/usr/LICENSE

The license should be at /usr/share/licenses.

**Comment by ihabunek** [comment] 2020-01-21 13:48
@dadosch I'm bad at packaging, if you have an idea how this should be done properly, a patch would be most appreciated.

**Comment by bill-auger** [comment] 2020-01-21 17:23
FWIW, there is no universal "should be" location - that is something specified in the packaging guidelines of each distro - if one follows the FHS for examnple, all user-installed files should go under /usr/local/ or /opt/, not /usr/ - /usr/ is for files installed by the distro maintainers, or the system package manager

i could not reproduce the problem reported in this ticket - no CHANGELOG.md or LICENSE files get installed on my system when building from the git tagged source-ball - e.g.:

  https://github.com/ihabunek/toot/archive/0.24.0.tar.gz

on my system, running these commands:
```
# python setup.py build
# python setup.py install --root="${pkgdir}/" --optimize=1 --skip-build
```
... installs the following files:
```
/usr/
/usr/bin/
/usr/bin/toot
/usr/lib/
/usr/lib/python3.8/
/usr/lib/python3.8/site-packages/
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/PKG-INFO
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/SOURCES.txt
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/dependency_links.txt
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/entry_points.txt
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/requires.txt
/usr/lib/python3.8/site-packages/toot-0.24.0-py3.8.egg-info/top_level.txt
/usr/lib/python3.8/site-packages/toot/
/usr/lib/python3.8/site-packages/toot/__init__.py
/usr/lib/python3.8/site-packages/toot/__pycache__/
/usr/lib/python3.8/site-packages/toot/__pycache__/__init__.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/__init__.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/api.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/api.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/auth.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/auth.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/commands.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/commands.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/config.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/config.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/console.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/console.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/exceptions.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/exceptions.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/http.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/http.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/logging.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/logging.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/output.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/output.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/utils.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/utils.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/wcstring.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/__pycache__/wcstring.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/api.py
/usr/lib/python3.8/site-packages/toot/auth.py
/usr/lib/python3.8/site-packages/toot/commands.py
/usr/lib/python3.8/site-packages/toot/config.py
/usr/lib/python3.8/site-packages/toot/console.py
/usr/lib/python3.8/site-packages/toot/exceptions.py
/usr/lib/python3.8/site-packages/toot/http.py
/usr/lib/python3.8/site-packages/toot/logging.py
/usr/lib/python3.8/site-packages/toot/output.py
/usr/lib/python3.8/site-packages/toot/tui/
/usr/lib/python3.8/site-packages/toot/tui/__init__.py
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/__init__.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/__init__.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/app.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/app.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/compose.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/compose.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/constants.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/constants.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/entities.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/entities.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/overlays.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/overlays.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/timeline.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/timeline.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/utils.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/utils.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/widgets.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/tui/__pycache__/widgets.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/tui/app.py
/usr/lib/python3.8/site-packages/toot/tui/compose.py
/usr/lib/python3.8/site-packages/toot/tui/constants.py
/usr/lib/python3.8/site-packages/toot/tui/entities.py
/usr/lib/python3.8/site-packages/toot/tui/overlays.py
/usr/lib/python3.8/site-packages/toot/tui/timeline.py
/usr/lib/python3.8/site-packages/toot/tui/utils.py
/usr/lib/python3.8/site-packages/toot/tui/widgets.py
/usr/lib/python3.8/site-packages/toot/ui/
/usr/lib/python3.8/site-packages/toot/ui/__init__.py
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/__init__.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/__init__.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/app.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/app.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/parsers.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/parsers.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/utils.cpython-38.opt-1.pyc
/usr/lib/python3.8/site-packages/toot/ui/__pycache__/utils.cpython-38.pyc
/usr/lib/python3.8/site-packages/toot/ui/app.py
/usr/lib/python3.8/site-packages/toot/ui/parsers.py
/usr/lib/python3.8/site-packages/toot/ui/utils.py
/usr/lib/python3.8/site-packages/toot/utils.py
/usr/lib/python3.8/site-packages/toot/wcstring.py
```

**Comment by dadosch** [comment] 2020-01-21 21:06
> i could not reproduce the problem reported in this ticket - no CHANGELOG.md or LICENSE files get installed on my system when building from the git tagged source-ball - e.g.:

It was introduced in the latest 0.25.0 release.


 ```
# mkdir outdir
 # python setup.py build
# python setup.py install --root="outdir/" --optimize=1 --skip-build
 ```

For the latest 0.25.0 release, these commands create the files at outdir/usr/ (CHANGELOG.md | LICENSE) for me.


> FWIW, there is no universal "should be" location - that is something specified in the packaging guidelines of each distro - if one follows the FHS for examnple, all user-installed files should go under /usr/local/ or /opt/, not /usr/ - /usr/ is for files installed by the distro maintainers, or the system package manager

Yes, but when calling `python setup.py install` those files (CHANGELOG.md and LICENSE) get added to the system to the wrong location. Where setuptools installs the binaries is a different story.

**Comment by bill-auger** [comment] 2020-01-22 03:20
ah yea - i did not realize at the time that there was a new release - the difference is exactly those two files

/usr/CHANGELOG.md
/usr/LICENSE

**Comment by ihabunek** [comment] 2020-01-22 07:07
If you don't have a better idea, I'll revert the change which added the two files to the package.

**Comment by dadosch** [comment] 2020-01-22 14:56
> If you don't have a better idea, I'll revert the change which added the two files to the package.

No, I don't have a better idea.

I think it is fine to have the changelog and License only in the source .tar.gz archive.

**Comment by linxon** [comment] 2020-01-22 15:07
```diff
diff -ur a/setup.py b/setup.py
--- a/setup.py	2020-01-21 11:46:09.000000000 +0300
+++ b/setup.py	2020-01-22 18:03:22.364999305 +0300
@@ -47,8 +47,5 @@
         'console_scripts': [
             'toot=toot.console:main',
         ],
-    },
-    data_files=[
-        ("", ["LICENSE", "CHANGELOG.md"])
-    ]
+    }
 )
```

**Comment by bill-auger** [comment] 2020-01-22 17:18
there seems to be some confusion about, on the one hand, which
files go into the duplicate source-ball, and on the other hand,
which files get installed with `setup.py install` - those are
rarely the same set of files - i read the python setuptools
documents to learn a bit more about this - from what i learned,
the python way to create a source-ball is with the `setup.py
sdist` command - the files that will be put into the source-ball
are not related to anything in the setup.py script - that is
determined only by the MANIFEST.in file; which in this case,
specifies every file in the source tree (the recursive '*') -
the 'data_files' key in setup.py is for specifying files that
will be installed with `setup.py install`

i ran `setup.py sdist` after removing the 'data_files' entry
(just as it was not there in 0.24.0) and all files in the source
tree were in the generated source-ball, just as the setuptools
docs promised; so im not sure why there was ever any discrepancy
- the 0.24.0 source-ball must have been generated some other way
than either setuptools or git

`setup.py sdist` is only particularly useful if you want to
specify exactly which files go into  the source-ball and which
do not - if every file in the source tree goes into the
source-ball, then `git archive <TAG>` would do the same thing -
it produces a source-ball identical to the one that github
auto-generates for each git tag; which is why i mentioned on the
other ticket, that it is totally redundant to create and upload
a source-ball manually

in some cases, the maintainer may want to remove some files from
the source-ball, that are in the development tree, such as the
CI mete-data; but it is rarely strictly necessary - that is just
a matter of tidiness

if every file in the source tree is to be into the source-ball,
then there is absolutely no reason to do that manually - it
would only be an exact duplicate of the one that github
generated automatically for the git tag - 

all that is needed to solve this problem entirely, is to revert
the change that introduced the 'data_files' entry, and simply
stop creating duplicate source-balls manually - if you must make
a duplicate, run either `git archive <TAG>`, or `setup.py sdist`
- im pretty sure they will produce the same thing, and both will
include all files in the source tree; and should be identical to
the auto-generated one

BTW, i found a way to get the license and changelog installed in
the package - apparently python does not have a straight-forward
way to do that - i found a way though; and i would suggest
installing them - the GPL does expect that each users gets a
copy of the LICENSE - that is not the issue of this ticket
though - let me know if you would like that feature

**Comment by ihabunek** [comment] 2020-01-23 12:31
Removed for now in https://github.com/ihabunek/toot/releases/tag/0.25.2

**Closed by ihabunek** 2020-01-23 12:31 UTC
