### ISSUE TITLE
tui Jumps to top when Posting

### ISSUE THREAD

**Issue by JRGonz** [ihabunek/toot#290] opened 2023-01-15 00:15 UTC
toot tui always jumps to the top of the list when posting (composing / replying / replying from thread). Would it be possible for it to stay on the post that you are actively reading instead?

**Comment by danschwarz** [comment] 2023-01-15 00:33
This is a duplicate of #188

**Comment by ihabunek** [comment] 2023-01-19 08:35
Resolved in c5b3724015ec1107fe48e6f273a753e05ba87d4d

**Closed by ihabunek** 2023-01-19 08:35 UTC
