### ISSUE TITLE
Using toot post in a cron => unrecognized argument

### ISSUE THREAD

**Issue by chaica** [ihabunek/toot#13] opened 2017-05-01 17:07 UTC
Hi,

I'm trying to use the toot post command in a cron, but each time I do have the following error

My script : 
```
#!/bin/bash
toot post -m /home/tootpost/mastodon.png "do you think #Mastodon community is great? Follow @mastodoncommunity@mastodon.social for the lastest news about mastodon community"
exit 0
```
My line in /etc/crontab
```
0 18 * * 1 tootpost /home/tootpost/postmasto.sh
```

Each time I get the following message in the cron error email: 
```
usage: toot post [-h] [-m MEDIA] [-v VISIBILITY] text
toot post: error: unrecognized arguments: 
```

Launching /home/tootpost/postmasto.sh by hand from the user tootpost provides the expected result.

I'm suspecting either an obvious mistake from my side either a required missing environment variable while launching from the cron.

**Comment by ihabunek** [comment] 2017-05-07 08:01
Duplicate of #11. Closing.

**Closed by ihabunek** 2017-05-07 08:01 UTC
