### ISSUE TITLE
Emojis in account name causes crash

### ISSUE THREAD

**Issue by albocc** [ihabunek/toot#21] opened 2017-07-06 22:19 UTC
After a successful login (I used `login_2fa`, but I don't think it matters) the application crashes, if the account name contains non-ASCII characters. If I run `toot whoami` to provoke this, I get the following error messages that seems to indicate that non-ASCII characters are a problem:

```
# toot whoami
Traceback (most recent call last):
  File "/usr/local/bin/toot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 285, in main
    run_command(app, user, command_name, args)
  File "/usr/local/lib/python3.6/site-packages/toot/console.py", line 262, in run_command
    return fn(app, user, parsed_args)
  File "/usr/local/lib/python3.6/site-packages/toot/commands.py", line 350, in whoami
    _print_account(account)
  File "/usr/local/lib/python3.6/site-packages/toot/commands.py", line 293, in _print_account
    print_out("<green>@{}</green> {}".format(account['acct'], account['display_name']))
  File "/usr/local/lib/python3.6/site-packages/toot/output.py", line 49, in print_out
    print(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f50f' in position 18: ordinal not in range(128)
```

**Comment by ihabunek** [comment] 2018-01-02 11:40
@albocc Could you tell me if this still happens with latest version? I'm unable to reproduce. Tried adding various unicode to my display name, including the one in question above `0001f50f`  🔏.

**Comment by ihabunek** [comment] 2018-01-05 16:49
This should be fixed. Please reopen if this is not the case.

**Closed by ihabunek** 2018-01-05 16:49 UTC
