### ISSUE TITLE
[feature] support cross-instance reblog

### ISSUE THREAD

**Issue by strk** [ihabunek/toot#494] opened 2024-07-24 05:21 UTC
I was surprised I couldn't do this:

> toot --as strk@infosec.exchange reblog https://floss.social/@strk/112839700329481329

Repeating toots across servers is something I always do with other clients, with more or less steps involved (#Tusky makes it the smoothest).

The problem is two fold:

  1. Status references are expected as just numbers (`112839700329481329` in this case)
  2. Status are searched only on the instance you are sending the command to
 
I don't know the internals of how reblogging/retooting/repeating but I feel cross-instance distribution of toots is a 1st class citizen of the fediverse so would be nice if toot supported that.

**Comment by ihabunek** [comment] 2024-08-12 09:43
Duplicate of #386, I'll continue the discussion there.

**Closed by ihabunek** 2024-08-12 09:43 UTC
